#!/bin/bash

FOLDER_PATH=$1
FILE_f=$2
G_CODE=$3
G_SIZE=$4
KINGDOM=$5
FOLDER_NAME=$6
METAGENOME=$7
PROJECT_NAME=$8
BUSCO_DB=$9
MAILADDR=${10}
num1=20000
num2=50000
SCRIPT_PATH="/home/pCAPS/scripts"

mkdir $FOLDER_PATH/annolog
python $SCRIPT_PATH/others/modi_id.py $FOLDER_PATH $FILE_f

if [ "$METAGENOME" == "1" ] 
then
	$SCRIPT_PATH/script_ms.sh $FOLDER_PATH $FILE_f $G_CODE $KINGDOM $FOLDER_NAME $PROJECT_NAME $BUSCO_DB $MAILADDR

else
	if [ $G_SIZE -ge $num1 ]
	then
		if [ $G_SIZE -lt $num2 ]
		then
		$SCRIPT_PATH/script_ss.sh $FOLDER_PATH $FILE_f $G_CODE $KINGDOM $FOLDER_NAME $PROJECT_NAME $BUSCO_DB $MAILADDR
		else
		$SCRIPT_PATH/script_sl.sh $FOLDER_PATH $FILE_f $G_CODE $KINGDOM $FOLDER_NAME $PROJECT_NAME $BUSCO_DB $MAILADDR
		fi
	else
	$SCRIPT_PATH/script_ms.sh $FOLDER_PATH $FILE_f $G_CODE $KINGDOM $FOLDER_NAME $PROJECT_NAME $BUSCO_DB $MAILADDR
	fi
fi


